### ISSUE TITLE
How do I actually run it?

### ISSUE THREAD

**Issue by amackenzie10** [Shmoopty/rpi-appliance-monitor#53]
Sorry I"m brand new to this and have installed everything but I'm not sure how to actually run it and use the program.

**Comment by Shmoopty** [comment]
To run it once, for testing, run

     python /home/pi/vibration.py /home/pi/vibration_settings.ini

(That's assuming `/home/pi` is the location of those files on your system.

If everything is working as you like, you can have it run automatically on startup with the similar-looking "Edit /etc/rc.local" step in the instructions.

**Comment by Ausmack** [comment]
Honestly didn't think I'd get a response, thank you so much for that! 

This is what happens when I run it and here's what I took from GitHub.   

Even if I get past that I get another modulenotfounderror.

Any ideas? 
![20210922_124651](https://user-images.githubusercontent.com/91149392/134391639-7c0d1961-a2f0-4aec-a82e-9f3fc1525744.jpg)
![20210922_125158](https://user-images.githubusercontent.com/91149392/134391643-551415dc-8204-4ddd-bd16-24401d7715a4.jpg)
![20210922_125645](https://user-images.githubusercontent.com/91149392/134391646-ff1911b9-e612-4283-add0-a50226a8c26e.jpg)

**Comment by Shmoopty** [comment]
python /home/pi/vibration.py /home/pi/vibration_settings.ini

should be entered exactly, as one line.

It looks like you pressed [Enter] before completing that line.  As if you had typed

     python /home/pi/vibration.py
     /home/pi/vibration_settings.ini

**Comment by Ausmack** [comment]
![20210922_140742](https://user-images.githubusercontent.com/91149392/134400848-740fbf0f-96e4-443a-9537-c6be021f60e7.jpg)

I got this message. I did check to confirm the files are exact too.

**Comment by Ausmack** [comment]
With the new vibration.py it works flawless.. Thank you
